"""Tango API Python SDK"""

from .client import TangoClient
from .exceptions import (
    TangoAPIError,
    TangoAuthError,
    TangoNotFoundError,
    TangoRateLimitError,
    TangoValidationError,
)
from .models import (
    BudgetAccount,
    GsaElibraryContract,
    ITDashboardInvestment,
    PaginatedResponse,
    RateLimitInfo,
    ResolveCandidate,
    ResolveResult,
    SearchFilters,
    ShapeConfig,
    ValidateResult,
    Vehicle,
    VehicleMetrics,
    WebhookAlert,
    WebhookEndpoint,
    WebhookEventType,
    WebhookEventTypesResponse,
    WebhookSampleDelivery,
    WebhookSamplePayloadAllResponse,
    WebhookSamplePayloadResponse,
    WebhookSamplePayloadSingleResponse,
    WebhookTestDeliveryResult,
)
from .shapes import (
    ModelFactory,
    SchemaRegistry,
    ShapeParser,
    TypeGenerator,
)
from .webhooks import (
    generate_signature,
    parse_signature_header,
    verify_signature,
)
from .webhooks.receiver import Delivery, WebhookReceiver

__version__ = "1.1.3"
__all__ = [
    "TangoClient",
    "TangoAPIError",
    "TangoAuthError",
    "TangoNotFoundError",
    "TangoValidationError",
    "TangoRateLimitError",
    "RateLimitInfo",
    "ResolveCandidate",
    "ResolveResult",
    "BudgetAccount",
    "GsaElibraryContract",
    "ITDashboardInvestment",
    "PaginatedResponse",
    "SearchFilters",
    "ShapeConfig",
    "ValidateResult",
    "Vehicle",
    "VehicleMetrics",
    "WebhookAlert",
    "WebhookEndpoint",
    "WebhookEventType",
    "WebhookEventTypesResponse",
    "WebhookSampleDelivery",
    "WebhookSamplePayloadAllResponse",
    "WebhookSamplePayloadResponse",
    "WebhookSamplePayloadSingleResponse",
    "WebhookTestDeliveryResult",
    "ShapeParser",
    "ModelFactory",
    "TypeGenerator",
    "SchemaRegistry",
    "Delivery",
    "WebhookReceiver",
    "generate_signature",
    "parse_signature_header",
    "verify_signature",
]
