#!/usr/bin/env python3
"""
Validate tango-python SDK against the canonical API filter/shape manifest.

This script reads the API contract (generated by tango, vendored at
contracts/filter_shape_contract.json, refreshed via scripts/refresh_contract.py)
and checks that the SDK methods conform to it. The SDK owns the mapping of
resources to methods and the parameter name translations.

Conformance checks:
1. Coverage: every runtime filter param in the contract is exposed by the
   mapped SDK method (explicit argument or via `api_param_mapping`). Missing
   params are errors unless accepted in contracts/conformance_baseline.json
   (then warnings — a tracked backlog, not silent drift).
2. Staleness: every filter-like SDK argument resolves to a param the API
   actually accepts. A stale param silently no-ops for users, so this is
   always an error.
3. Types: when the contract carries type metadata (schema_version >= 2), each
   SDK argument's annotation must be compatible with the contract value type.
4. Shapes: every ShapeConfig constant parses and validates against the SDK
   schema for its model (so default shapes only reference allowed fields).

Usage:
    uv run python scripts/check_filter_shape_conformance.py
    uv run python scripts/check_filter_shape_conformance.py --manifest path/to/contract.json
    uv run python scripts/check_filter_shape_conformance.py --suggest
"""

from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
CLIENT_PATH = REPO_ROOT / "tango" / "client.py"
DEFAULT_MANIFEST_PATH = REPO_ROOT / "contracts" / "filter_shape_contract.json"
BASELINE_PATH = REPO_ROOT / "contracts" / "conformance_baseline.json"


# ---------------------------------------------------------------------------
# Resource → SDK method mapping
# ---------------------------------------------------------------------------
# The SDK decides which method handles which API resources. This mapping is
# owned by tango-python, not inferred by the API.

RESOURCE_TO_METHOD: dict[str, str | None] = {
    # list_* methods
    "contracts": "list_contracts",
    "idvs": "list_idvs",
    "vehicles": "list_vehicles",
    "otas": "list_otas",
    "otidvs": "list_otidvs",
    "subawards": "list_subawards",
    "organizations": "list_organizations",
    "opportunities": "list_opportunities",
    "notices": "list_notices",
    "forecasts": "list_forecasts",
    "grants": "list_grants",
    "entities": "list_entities",
    "agencies": "list_agencies",
    "naics": "list_naics",
    "gsa_elibrary_contracts": "list_gsa_elibrary_contracts",
    "itdashboard": "list_itdashboard_investments",
    # Nested routes are keyed with a slash in the contract ("budget/accounts").
    # The pre-slash key is kept so an older vendored contract still maps.
    "budget/accounts": "list_budget_accounts",
    "budget_accounts": "list_budget_accounts",
    "dibbs/rfqs": "list_dibbs_rfqs",
    "dibbs/rfps": "list_dibbs_rfps",
    "dibbs/awards": "list_dibbs_awards",
    "exclusions": "list_exclusions",
    "sbir/topics": "list_sbir_topics",
    "sbir/solicitations": "list_sbir_solicitations",
    # Resources not yet implemented in SDK
    "offices": None,
}

# Params the API genuinely accepts but the contract omits, so they would read as
# stale (a silent no-op) when they in fact work. Tango surfaces view-handled
# search params for filtersets that declare `min_length_params`; where it does
# not, the param is absent from the contract even though the endpoint honors it.
# Each entry must be verified against the live API before being added, and
# removed once Tango's contract generator surfaces it.
#   budget/accounts `search`: verified 2026-07-19 — 21,170 results unfiltered vs
#   0 for a nonsense term, so the endpoint clearly applies it.
CONTRACT_OMITTED_PARAMS: dict[str, frozenset[str]] = {
    "budget/accounts": frozenset({"search"}),
}

# SDK-level conveniences that never correspond to API filter params.
# `sort`/`order` compose into the API's `ordering`; `filters` is the legacy
# SearchFilters escape hatch; the rest are pagination/shaping controls.
NON_FILTER_ARGS = {
    "cursor",
    "limit",
    "page",
    "shape",
    "flat",
    "flat_lists",
    "joiner",
    "filters",
    "sort",
    "order",
    "verbose",
}

# Contract value type → acceptable Python annotation base types.
# Dates/datetimes are passed as ISO strings in this SDK; numbers are accepted
# as int, float, or string (amounts are conventionally strings). `string` is
# the contract's catch-all (custom API filters often subclass CharFilter for
# numeric/boolean semantics), so it does not constrain the SDK annotation.
TYPE_COMPAT: dict[str, set[str] | None] = {
    "string": None,
    "choice": {"str"},
    "ordering": {"str"},
    "date": {"str"},
    "datetime": {"str"},
    "time": {"str"},
    "number": {"int", "float", "str"},
    "boolean": {"bool"},
}

# Contract value type → suggested annotation for --suggest scaffolds.
SUGGESTED_ANNOTATION: dict[str, str] = {
    "string": "str | None",
    "choice": "str | None",
    "ordering": "str | None",
    "date": "str | None",
    "datetime": "str | None",
    "time": "str | None",
    "number": "str | None",
    "boolean": "bool | None",
}


def get_shape_config_entries() -> list[tuple[str, str, type[Any]]]:
    """Return (shape_name, shape_string, model_class) for every ShapeConfig constant."""
    from tango.models import (
        IDV,
        OTA,
        OTIDV,
        BudgetAccount,
        Contract,
        Entity,
        Forecast,
        Grant,
        GsaElibraryContract,
        ITDashboardInvestment,
        Notice,
        Opportunity,
        Organization,
        ShapeConfig,
        Subaward,
        Vehicle,
    )

    # ShapeConfig constant name -> (shape string, model class for validation)
    entries: list[tuple[str, str, type[Any]]] = []
    configs = [
        ("CONTRACTS_MINIMAL", ShapeConfig.CONTRACTS_MINIMAL, Contract),
        ("ENTITIES_MINIMAL", ShapeConfig.ENTITIES_MINIMAL, Entity),
        ("ENTITIES_COMPREHENSIVE", ShapeConfig.ENTITIES_COMPREHENSIVE, Entity),
        ("FORECASTS_MINIMAL", ShapeConfig.FORECASTS_MINIMAL, Forecast),
        ("OPPORTUNITIES_MINIMAL", ShapeConfig.OPPORTUNITIES_MINIMAL, Opportunity),
        ("NOTICES_MINIMAL", ShapeConfig.NOTICES_MINIMAL, Notice),
        ("GRANTS_MINIMAL", ShapeConfig.GRANTS_MINIMAL, Grant),
        ("IDVS_MINIMAL", ShapeConfig.IDVS_MINIMAL, IDV),
        ("IDVS_COMPREHENSIVE", ShapeConfig.IDVS_COMPREHENSIVE, IDV),
        ("VEHICLES_MINIMAL", ShapeConfig.VEHICLES_MINIMAL, Vehicle),
        ("VEHICLES_COMPREHENSIVE", ShapeConfig.VEHICLES_COMPREHENSIVE, Vehicle),
        ("VEHICLE_AWARDEES_MINIMAL", ShapeConfig.VEHICLE_AWARDEES_MINIMAL, IDV),
        ("ORGANIZATIONS_MINIMAL", ShapeConfig.ORGANIZATIONS_MINIMAL, Organization),
        ("OTAS_MINIMAL", ShapeConfig.OTAS_MINIMAL, OTA),
        ("OTIDVS_MINIMAL", ShapeConfig.OTIDVS_MINIMAL, OTIDV),
        ("SUBAWARDS_MINIMAL", ShapeConfig.SUBAWARDS_MINIMAL, Subaward),
        (
            "GSA_ELIBRARY_CONTRACTS_MINIMAL",
            ShapeConfig.GSA_ELIBRARY_CONTRACTS_MINIMAL,
            GsaElibraryContract,
        ),
        (
            "ITDASHBOARD_INVESTMENTS_MINIMAL",
            ShapeConfig.ITDASHBOARD_INVESTMENTS_MINIMAL,
            ITDashboardInvestment,
        ),
        (
            "ITDASHBOARD_INVESTMENTS_COMPREHENSIVE",
            ShapeConfig.ITDASHBOARD_INVESTMENTS_COMPREHENSIVE,
            ITDashboardInvestment,
        ),
        ("BUDGET_ACCOUNTS_MINIMAL", ShapeConfig.BUDGET_ACCOUNTS_MINIMAL, BudgetAccount),
    ]
    for name, shape_str, model_cls in configs:
        entries.append((name, shape_str, model_cls))
    return entries


def run_shape_check() -> tuple[list[str], list[str]]:
    """Validate all ShapeConfig constants against SDK schemas. Returns (errors, warnings)."""
    from tango.exceptions import ShapeParseError, ShapeValidationError
    from tango.shapes.parser import ShapeParser

    errors: list[str] = []
    warnings: list[str] = []
    parser = ShapeParser(cache_enabled=True)

    for shape_name, shape_string, model_class in get_shape_config_entries():
        try:
            shape_spec = parser.parse(shape_string)
            parser.validate(shape_spec, model_class)
        except ShapeParseError as e:
            errors.append(f"shapes: `ShapeConfig.{shape_name}` parse error: {e}")
        except ShapeValidationError as e:
            errors.append(f"shapes: `ShapeConfig.{shape_name}` invalid: {e}")

    return errors, warnings


def parse_client_methods() -> dict[str, dict[str, Any]]:
    """Parse SDK client methods and extract arguments, annotations, and API param mappings."""
    tree = ast.parse(CLIENT_PATH.read_text(encoding="utf-8"), filename=str(CLIENT_PATH))
    methods: dict[str, dict[str, Any]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        if not node.name.startswith(("list_", "get_")):
            continue
        arg_nodes = [arg for arg in (node.args.args + node.args.kwonlyargs) if arg.arg != "self"]
        args = [arg.arg for arg in arg_nodes]
        annotations = {
            arg.arg: ast.unparse(arg.annotation) for arg in arg_nodes if arg.annotation is not None
        }
        has_kwargs = node.args.kwarg is not None
        # Explicit `api_param_mapping` always wins over the inline forms below:
        # a method that has one routes its tuple keys THROUGH it
        # (`api_param_mapping.get(key, key)`), so there the tuple literal is the
        # SDK-side name, not the API param.
        explicit_mapping: dict[str, str] = {}
        inline_mapping: dict[str, str] = {}
        mapping: dict[str, str] = explicit_mapping
        for child in ast.walk(node):
            if isinstance(child, ast.Assign):
                if len(child.targets) != 1 or not isinstance(child.targets[0], ast.Name):
                    continue
                if child.targets[0].id != "api_param_mapping":
                    continue
                if isinstance(child.value, ast.Dict):
                    for key, value in zip(child.value.keys, child.value.values, strict=True):
                        if isinstance(key, ast.Constant) and isinstance(value, ast.Constant):
                            mapping[str(key.value)] = str(value.value)

            # Methods also express the arg -> API-param translation as tuple
            # tables rather than an api_param_mapping dict. These must be
            # understood or their args look stale, when in fact they resolve to a
            # param the API does accept under a different name. Two element
            # shapes appear, in inline `for ... in (...)` iterables and in named
            # tables (`scalar_filters = (...)`, `range_filters: tuple[...] = (...)`,
            # so both Assign and AnnAssign):
            #
            #   ("account_title__icontains", account_title)
            #       -> the literal is the API param, the Name is the SDK argument.
            #
            #   ("apportioned", apportioned, apportioned_gte, apportioned_lte)
            #       -> the loop emits field / field__gte / field__lte, so the three
            #          Names map onto those three API params in order.
            table: ast.expr | None = None
            if isinstance(child, ast.For):
                table = child.iter
            elif isinstance(child, ast.Assign):
                table = child.value
            elif isinstance(child, ast.AnnAssign):
                table = child.value
            if isinstance(table, ast.Tuple | ast.List):
                for elt in table.elts:
                    if not isinstance(elt, ast.Tuple) or not elt.elts:
                        continue
                    head = elt.elts[0]
                    if not (isinstance(head, ast.Constant) and isinstance(head.value, str)):
                        continue
                    if len(elt.elts) == 2 and isinstance(elt.elts[1], ast.Name):
                        inline_mapping[elt.elts[1].id] = head.value
                    elif len(elt.elts) == 4:
                        for name_node, suffix in zip(
                            elt.elts[1:], ("", "__gte", "__lte"), strict=True
                        ):
                            if isinstance(name_node, ast.Name):
                                inline_mapping[name_node.id] = f"{head.value}{suffix}"
        mapping = {**inline_mapping, **explicit_mapping}
        methods[node.name] = {
            "args": set(args),
            "annotations": annotations,
            "has_kwargs": has_kwargs,
            "api_param_mapping": mapping,
            "mapped_api_params": set(mapping.values()),
        }
    return methods


def load_baseline() -> dict[str, Any]:
    """Load accepted-gaps baseline. Missing params listed here warn instead of error."""
    if not BASELINE_PATH.exists():
        return {"missing_filters": {}}
    baseline: dict[str, Any] = json.loads(BASELINE_PATH.read_text(encoding="utf-8"))
    baseline.setdefault("missing_filters", {})
    return baseline


def _annotation_base(annotation: str) -> str | None:
    """Reduce an annotation like `str | None` to its base type, if simple."""
    parts = [part.strip() for part in annotation.split("|")]
    parts = [part for part in parts if part != "None"]
    if len(parts) != 1:
        return None
    return parts[0] if parts[0] in {"str", "int", "float", "bool"} else None


def _exposed_api_params(method_info: dict[str, Any]) -> dict[str, str]:
    """Map each filter-like SDK argument to the API param it sends."""
    mapping: dict[str, str] = method_info["api_param_mapping"]
    return {arg: mapping.get(arg, arg) for arg in method_info["args"] if arg not in NON_FILTER_ARGS}


def run_check(manifest_path: Path) -> tuple[list[str], list[str]]:
    """Run filter conformance checks against the manifest."""
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    resources = manifest.get("resources", {})
    schema_version = int(manifest.get("meta", {}).get("schema_version", 1))
    methods = parse_client_methods()
    baseline = load_baseline()

    errors: list[str] = []
    warnings: list[str] = []

    if schema_version < 2:
        warnings.append(
            "manifest: schema_version < 2 (no filter type metadata) — type "
            "conformance skipped; refresh the contract via scripts/refresh_contract.py"
        )

    for resource_name, payload in resources.items():
        # Look up which SDK method handles this resource
        sdk_method = RESOURCE_TO_METHOD.get(resource_name)

        if sdk_method is None:
            # Explicitly marked as not implemented
            runtime_filters = payload.get("runtime", {}).get("filter_params", [])
            if runtime_filters:
                warnings.append(f"{resource_name}: no SDK method implemented for this resource")
            continue

        if sdk_method not in methods:
            # Method mapped but not found in client.py
            errors.append(f"{resource_name}: mapped method `{sdk_method}` not found in SDK client")
            continue

        runtime = payload.get("runtime", {})
        runtime_filters = set(runtime.get("filter_params", []))
        # `ordering` is accepted via DRF ordering backends (ordering_fields /
        # ordering_fields_map) even when no FilterSet declares it.
        if runtime.get("ordering_fields") or runtime.get("ordering_aliases"):
            runtime_filters.add("ordering")
        detail: dict[str, dict[str, Any]] = runtime.get("filter_params_detail", {})
        method_info = methods[sdk_method]
        exposed = _exposed_api_params(method_info)
        exposed_api = set(exposed.values())
        accepted_missing = set(baseline["missing_filters"].get(resource_name, []))

        if method_info["has_kwargs"]:
            missing_named = sorted(runtime_filters - exposed_api)
            if missing_named:
                warnings.append(
                    f"{resource_name}: `{sdk_method}` relies on **kwargs for filters: {', '.join(missing_named)}"
                )
            continue

        # Direction 1 — coverage: API accepts it, SDK doesn't expose it.
        missing = runtime_filters - exposed_api
        hard_missing = sorted(missing - accepted_missing)
        known_missing = sorted(missing & accepted_missing)
        if hard_missing:
            errors.append(
                f"{resource_name}: `{sdk_method}` missing runtime filters: {', '.join(hard_missing)}"
            )
        if known_missing:
            warnings.append(
                f"{resource_name}: `{sdk_method}` known gaps (baselined): {', '.join(known_missing)}"
            )
        stale_baseline = sorted(accepted_missing - missing)
        if stale_baseline:
            warnings.append(
                f"{resource_name}: baseline entries no longer needed: {', '.join(stale_baseline)}"
            )

        # Direction 2 — staleness: SDK sends it, API no longer accepts it.
        stale = sorted(
            f"{arg} (sends `{api_param}`)" if arg != api_param else arg
            for arg, api_param in exposed.items()
            if api_param not in runtime_filters
            and api_param not in CONTRACT_OMITTED_PARAMS.get(resource_name, frozenset())
        )
        if stale:
            errors.append(
                f"{resource_name}: `{sdk_method}` exposes params the API does not "
                f"accept (silent no-ops — deprecate or fix mapping): {', '.join(stale)}"
            )

        # `sort`/`order` compose into `ordering`; only valid if the API has it.
        if {"sort", "order"} & method_info["args"] and "ordering" not in runtime_filters:
            warnings.append(
                f"{resource_name}: `{sdk_method}` has sort/order args but the API "
                "exposes no `ordering` filter"
            )

        # Direction 3 — types (schema_version >= 2 only).
        if schema_version >= 2 and detail:
            for arg, api_param in sorted(exposed.items()):
                contract_type = detail.get(api_param, {}).get("type")
                if contract_type is None:
                    continue
                annotation = method_info["annotations"].get(arg)
                if annotation is None:
                    continue
                base = _annotation_base(annotation)
                if base is None:
                    continue  # complex annotation; not mechanically checkable
                allowed = TYPE_COMPAT.get(contract_type)
                if allowed and base not in allowed:
                    errors.append(
                        f"{resource_name}: `{sdk_method}({arg}: {annotation})` is "
                        f"incompatible with contract type `{contract_type}` for "
                        f"API param `{api_param}` (expected one of: {', '.join(sorted(allowed))})"
                    )

    return errors, warnings


def build_suggestions(manifest_path: Path) -> str:
    """Emit ready-to-paste typed parameter scaffolds for missing filters."""
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    resources = manifest.get("resources", {})
    methods = parse_client_methods()

    blocks: list[str] = []
    for resource_name, payload in sorted(resources.items()):
        sdk_method = RESOURCE_TO_METHOD.get(resource_name)
        if not sdk_method or sdk_method not in methods:
            continue
        runtime = payload.get("runtime", {})
        runtime_filters = set(runtime.get("filter_params", []))
        if runtime.get("ordering_fields") or runtime.get("ordering_aliases"):
            runtime_filters.add("ordering")
        detail: dict[str, dict[str, Any]] = runtime.get("filter_params_detail", {})
        exposed_api = set(_exposed_api_params(methods[sdk_method]).values())
        missing = sorted(runtime_filters - exposed_api)
        if not missing:
            continue

        sig_lines: list[str] = []
        tuple_lines: list[str] = []
        for param in missing:
            info = detail.get(param, {})
            contract_type = info.get("type", "string")
            annotation = SUGGESTED_ANNOTATION.get(contract_type, "str | None")
            comment_bits = [contract_type]
            if contract_type == "date":
                comment_bits.append("YYYY-MM-DD")
            if info.get("choices"):
                choices = info["choices"]
                shown = ", ".join(choices[:8])
                if len(choices) > 8:
                    shown += ", ..."
                comment_bits.append(f"one of: {shown}")
            sig_lines.append(f"        {param}: {annotation} = None,  # {'; '.join(comment_bits)}")
            tuple_lines.append(f'            ("{param}", {param}),')

        blocks.append(
            "\n".join(
                [
                    f"## {resource_name} → `{sdk_method}` — {len(missing)} missing param(s)",
                    "# signature additions:",
                    *sig_lines,
                    "# filter_params tuple additions:",
                    *tuple_lines,
                ]
            )
        )

    if not blocks:
        return "# No missing filters — SDK surface covers the contract."
    return "\n\n".join(blocks)


def get_unmapped_resources(manifest_path: Path) -> list[dict[str, Any]]:
    """Return a list of resources that have no SDK method mapped (for implementation checklist)."""
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    resources = manifest.get("resources", {})
    methods = parse_client_methods()
    unmapped: list[dict[str, Any]] = []

    for resource_name, payload in resources.items():
        sdk_method = RESOURCE_TO_METHOD.get(resource_name)

        # Check if unmapped or method doesn't exist
        if sdk_method is None or sdk_method not in methods:
            runtime = payload.get("runtime", {}) or {}
            unmapped.append(
                {
                    "resource": resource_name,
                    "expected_method": sdk_method,
                    "filter_params": runtime.get("filter_params", []),
                    "pagination_class": (runtime.get("pagination") or {}).get("class", ""),
                }
            )
    return unmapped


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check SDK conformance against canonical API manifest"
    )
    parser.add_argument(
        "--manifest",
        default=str(DEFAULT_MANIFEST_PATH),
        help=(
            "Path to filter_shape_contract.json (default: vendored copy at "
            "contracts/filter_shape_contract.json)"
        ),
    )
    parser.add_argument(
        "--list-unmapped",
        action="store_true",
        help="Output machine-readable list of unmapped resources (no SDK method) only",
    )
    parser.add_argument(
        "--suggest",
        action="store_true",
        help="Print ready-to-paste typed parameter scaffolds for missing filters",
    )
    args = parser.parse_args()

    manifest_path = Path(args.manifest).resolve()
    if not manifest_path.exists():
        print(f"Manifest not found: {manifest_path}")
        print("Vendor it with: uv run python scripts/refresh_contract.py")
        return 2

    if args.list_unmapped:
        unmapped = get_unmapped_resources(manifest_path)
        print(json.dumps({"unmapped_resources": unmapped}, indent=2))
        return 0

    if args.suggest:
        print(build_suggestions(manifest_path))
        return 0

    errors, warnings = run_check(manifest_path)

    # Shape conformance: every ShapeConfig constant must validate against its model schema
    shape_errors, shape_warnings = run_shape_check()
    errors = list(errors) + shape_errors
    warnings = list(warnings) + shape_warnings

    report = {
        "manifest": str(manifest_path),
        "errors": errors,
        "warnings": warnings,
    }
    print(json.dumps(report, indent=2))
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
