"""GENERATED by scripts/generate_shape_overlay.py — do not edit by hand.

Reverse shape-coverage overlay: the fields and expands Tango's shape trees
expose that the hand-curated explicit_schemas.py did not capture. SchemaRegistry
merges this over the base schemas so the SDK's typed shape API accepts everything
the API returns. Regenerate after refreshing the vendored contract or observations.
"""

from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401

from tango.shapes.schema import FieldSchema

ADDITIONAL_INFO_SCHEMA: dict[str, FieldSchema] = {
    "description": FieldSchema(name="description", type=str, is_optional=True, is_list=False),
    "link": FieldSchema(name="link", type=str, is_optional=True, is_list=False),
}

AGENCY_SCHEMA: dict[str, FieldSchema] = {
    "abbreviation": FieldSchema(name="abbreviation", type=str, is_optional=True, is_list=False),
    "code": FieldSchema(name="code", type=int, is_optional=True, is_list=False),
    "name": FieldSchema(name="name", type=str, is_optional=True, is_list=False),
}

AGENCY2_SCHEMA: dict[str, FieldSchema] = {
    "abbreviation": FieldSchema(name="abbreviation", type=str, is_optional=True, is_list=False),
    "code": FieldSchema(name="code", type=str, is_optional=True, is_list=False),
    "name": FieldSchema(name="name", type=str, is_optional=True, is_list=False),
}

ANCESTORS_SCHEMA: dict[str, FieldSchema] = {
    "fh_key": FieldSchema(name="fh_key", type=int, is_optional=True, is_list=False),
    "level": FieldSchema(name="level", type=int, is_optional=True, is_list=False),
    "name": FieldSchema(name="name", type=str, is_optional=True, is_list=False),
    "short_name": FieldSchema(name="short_name", type=str, is_optional=True, is_list=False),
}

ATTACHMENTS_SCHEMA: dict[str, FieldSchema] = {
    "attachment_id": FieldSchema(name="attachment_id", type=str, is_optional=True, is_list=False),
    "extracted_text": FieldSchema(name="extracted_text", type=str, is_optional=True, is_list=False),
    "file_size": FieldSchema(name="file_size", type=str, is_optional=True, is_list=False),
    "mime_type": FieldSchema(name="mime_type", type=str, is_optional=True, is_list=False),
    "name": FieldSchema(name="name", type=str, is_optional=True, is_list=False),
    "posted_date": FieldSchema(name="posted_date", type=date, is_optional=True, is_list=False),
    "resource_id": FieldSchema(name="resource_id", type=str, is_optional=True, is_list=False),
    "type": FieldSchema(name="type", type=str, is_optional=True, is_list=False),
    "url": FieldSchema(name="url", type=str, is_optional=True, is_list=False),
}

AWARDING_OFFICE_SCHEMA: dict[str, FieldSchema] = {
    "agency_code": FieldSchema(name="agency_code", type=str, is_optional=True, is_list=False),
    "agency_name": FieldSchema(name="agency_name", type=str, is_optional=True, is_list=False),
    "department_code": FieldSchema(
        name="department_code", type=str, is_optional=True, is_list=False
    ),
    "department_name": FieldSchema(
        name="department_name", type=str, is_optional=True, is_list=False
    ),
    "office_code": FieldSchema(name="office_code", type=str, is_optional=True, is_list=False),
    "office_name": FieldSchema(name="office_name", type=str, is_optional=True, is_list=False),
    "organization_id": FieldSchema(
        name="organization_id", type=str, is_optional=True, is_list=False
    ),
}

BUDGET_APPROPRIATION_SCHEMA: dict[str, FieldSchema] = {
    "cgac": FieldSchema(name="cgac", type=int, is_optional=True, is_list=False),
    "fiscal_year": FieldSchema(name="fiscal_year", type=int, is_optional=True, is_list=False),
    "n_accounts": FieldSchema(name="n_accounts", type=int, is_optional=True, is_list=False),
    "scope": FieldSchema(name="scope", type=str, is_optional=True, is_list=False),
    "summary": FieldSchema(name="summary", type=str, is_optional=True, is_list=False),
    "top_accounts": FieldSchema(name="top_accounts", type=str, is_optional=True, is_list=False),
}

BUDGET_SPENDING_SCHEMA: dict[str, FieldSchema] = {
    "fiscal_year": FieldSchema(name="fiscal_year", type=int, is_optional=True, is_list=False),
    "n_orgs_in_rollup": FieldSchema(
        name="n_orgs_in_rollup", type=int, is_optional=True, is_list=False
    ),
    "organization_id": FieldSchema(
        name="organization_id", type=str, is_optional=True, is_list=False
    ),
    "summary": FieldSchema(name="summary", type=str, is_optional=True, is_list=False),
    "top_accounts": FieldSchema(name="top_accounts", type=str, is_optional=True, is_list=False),
}

CHILDREN_SCHEMA: dict[str, FieldSchema] = {
    "cgac": FieldSchema(name="cgac", type=int, is_optional=True, is_list=False),
    "code": FieldSchema(name="code", type=int, is_optional=True, is_list=False),
    "fh_key": FieldSchema(name="fh_key", type=int, is_optional=True, is_list=False),
    "is_active": FieldSchema(name="is_active", type=bool, is_optional=True, is_list=False),
    "key": FieldSchema(name="key", type=str, is_optional=True, is_list=False),
    "level": FieldSchema(name="level", type=int, is_optional=True, is_list=False),
    "name": FieldSchema(name="name", type=str, is_optional=True, is_list=False),
    "short_name": FieldSchema(name="short_name", type=str, is_optional=True, is_list=False),
    "type": FieldSchema(name="type", type=str, is_optional=True, is_list=False),
}

CURRENT_SCHEMA: dict[str, FieldSchema] = {
    "active": FieldSchema(name="active", type=bool, is_optional=True, is_list=False),
    "description": FieldSchema(name="description", type=str, is_optional=True, is_list=False),
    "end_date": FieldSchema(name="end_date", type=str, is_optional=True, is_list=False),
    "excludes": FieldSchema(name="excludes", type=str, is_optional=True, is_list=False),
    "includes": FieldSchema(name="includes", type=str, is_optional=True, is_list=False),
    "name": FieldSchema(name="name", type=str, is_optional=True, is_list=False),
    "start_date": FieldSchema(name="start_date", type=date, is_optional=True, is_list=False),
}

DEPARTMENT_SCHEMA: dict[str, FieldSchema] = {
    "abbreviation": FieldSchema(name="abbreviation", type=str, is_optional=True, is_list=False),
    "cgac": FieldSchema(name="cgac", type=str, is_optional=True, is_list=False),
    "code": FieldSchema(name="code", type=int, is_optional=True, is_list=False),
    "congressional_justification": FieldSchema(
        name="congressional_justification", type=str, is_optional=True, is_list=False
    ),
    "description": FieldSchema(name="description", type=str, is_optional=True, is_list=False),
    "name": FieldSchema(name="name", type=str, is_optional=True, is_list=False),
    "website": FieldSchema(name="website", type=str, is_optional=True, is_list=False),
}

DEPARTMENT2_SCHEMA: dict[str, FieldSchema] = {
    "abbreviation": FieldSchema(name="abbreviation", type=str, is_optional=True, is_list=False),
    "cgac": FieldSchema(name="cgac", type=str, is_optional=True, is_list=False),
    "code": FieldSchema(name="code", type=str, is_optional=True, is_list=False),
    "congressional_justification": FieldSchema(
        name="congressional_justification", type=str, is_optional=True, is_list=False
    ),
    "description": FieldSchema(name="description", type=str, is_optional=True, is_list=False),
    "name": FieldSchema(name="name", type=str, is_optional=True, is_list=False),
    "website": FieldSchema(name="website", type=str, is_optional=True, is_list=False),
}

DISPLAY_SCHEMA: dict[str, FieldSchema] = {
    "agency": FieldSchema(name="agency", type=str, is_optional=True, is_list=False),
    "anticipated_award_date": FieldSchema(
        name="anticipated_award_date", type=date, is_optional=True, is_list=False
    ),
    "contract_vehicle": FieldSchema(
        name="contract_vehicle", type=str, is_optional=True, is_list=False
    ),
    "description": FieldSchema(name="description", type=str, is_optional=True, is_list=False),
    "estimated_period": FieldSchema(
        name="estimated_period", type=str, is_optional=True, is_list=False
    ),
    "fiscal_year": FieldSchema(name="fiscal_year", type=int, is_optional=True, is_list=False),
    "naics_code": FieldSchema(name="naics_code", type=int, is_optional=True, is_list=False),
    "place_of_performance": FieldSchema(
        name="place_of_performance", type=str, is_optional=True, is_list=False
    ),
    "primary_contact": FieldSchema(
        name="primary_contact", type=str, is_optional=True, is_list=False
    ),
    "set_aside": FieldSchema(name="set_aside", type=str, is_optional=True, is_list=False),
    "status": FieldSchema(name="status", type=str, is_optional=True, is_list=False),
    "title": FieldSchema(name="title", type=str, is_optional=True, is_list=False),
}

FEDERAL_OBLIGATIONS_SCHEMA: dict[str, FieldSchema] = {
    "active": FieldSchema(name="active", type=str, is_optional=True, is_list=False),
    "total": FieldSchema(name="total", type=str, is_optional=True, is_list=False),
}

FUNDING_DETAILS_SCHEMA: dict[str, FieldSchema] = {
    "award_ceiling": FieldSchema(name="award_ceiling", type=int, is_optional=True, is_list=False),
    "award_floor": FieldSchema(name="award_floor", type=int, is_optional=True, is_list=False),
    "estimated_total_funding": FieldSchema(
        name="estimated_total_funding", type=int, is_optional=True, is_list=False
    ),
    "expected_number_of_awards": FieldSchema(
        name="expected_number_of_awards", type=int, is_optional=True, is_list=False
    ),
}

GRANTOR_CONTACT_SCHEMA: dict[str, FieldSchema] = {
    "email": FieldSchema(name="email", type=str, is_optional=True, is_list=False),
    "name": FieldSchema(name="name", type=str, is_optional=True, is_list=False),
    "phone": FieldSchema(name="phone", type=str, is_optional=True, is_list=False),
}

GSA_ELIBRARY_SCHEMA: dict[str, FieldSchema] = {
    "contract_number": FieldSchema(
        name="contract_number", type=str, is_optional=True, is_list=False
    ),
    "cooperative_purchasing": FieldSchema(
        name="cooperative_purchasing", type=bool, is_optional=True, is_list=False
    ),
    "disaster_recovery_purchasing": FieldSchema(
        name="disaster_recovery_purchasing", type=bool, is_optional=True, is_list=False
    ),
    "external_id": FieldSchema(name="external_id", type=str, is_optional=True, is_list=False),
    "extracted_text": FieldSchema(name="extracted_text", type=str, is_optional=True, is_list=False),
    "file_urls": FieldSchema(name="file_urls", type=str, is_optional=True, is_list=True),
    "schedule": FieldSchema(name="schedule", type=str, is_optional=True, is_list=False),
    "sins": FieldSchema(name="sins", type=int, is_optional=True, is_list=True),
    "source_data": FieldSchema(name="source_data", type=str, is_optional=True, is_list=False),
    "uei": FieldSchema(name="uei", type=str, is_optional=True, is_list=False),
}

HISTORICAL_SCHEMA: dict[str, FieldSchema] = {
    "active": FieldSchema(name="active", type=bool, is_optional=True, is_list=False),
    "description": FieldSchema(name="description", type=str, is_optional=True, is_list=False),
    "end_date": FieldSchema(name="end_date", type=date, is_optional=True, is_list=False),
    "excludes": FieldSchema(name="excludes", type=str, is_optional=True, is_list=False),
    "includes": FieldSchema(name="includes", type=str, is_optional=True, is_list=False),
    "name": FieldSchema(name="name", type=str, is_optional=True, is_list=False),
    "start_date": FieldSchema(name="start_date", type=date, is_optional=True, is_list=False),
}

IMPORTANT_DATES_SCHEMA: dict[str, FieldSchema] = {
    "estimated_application_response_date": FieldSchema(
        name="estimated_application_response_date", type=date, is_optional=True, is_list=False
    ),
    "estimated_application_response_date_description": FieldSchema(
        name="estimated_application_response_date_description",
        type=str,
        is_optional=True,
        is_list=False,
    ),
    "estimated_project_start_date": FieldSchema(
        name="estimated_project_start_date", type=date, is_optional=True, is_list=False
    ),
    "estimated_synopsis_post_date": FieldSchema(
        name="estimated_synopsis_post_date", type=date, is_optional=True, is_list=False
    ),
    "posted_date": FieldSchema(name="posted_date", type=date, is_optional=True, is_list=False),
    "response_date": FieldSchema(name="response_date", type=date, is_optional=True, is_list=False),
    "response_date_description": FieldSchema(
        name="response_date_description", type=str, is_optional=True, is_list=False
    ),
}

LATEST_NOTICE_SCHEMA: dict[str, FieldSchema] = {
    "link": FieldSchema(name="link", type=str, is_optional=True, is_list=False),
    "notice_id": FieldSchema(name="notice_id", type=str, is_optional=True, is_list=False),
}

META_SCHEMA: dict[str, FieldSchema] = {
    "attachments_count": FieldSchema(
        name="attachments_count", type=int, is_optional=True, is_list=False
    ),
    "notice_type": FieldSchema(
        name="notice_type", type=dict, is_optional=True, is_list=False, nested_model="NoticeType"
    ),
    "notices_count": FieldSchema(name="notices_count", type=int, is_optional=True, is_list=False),
}

NOTICE_HISTORY_SCHEMA: dict[str, FieldSchema] = {
    "deleted": FieldSchema(name="deleted", type=str, is_optional=True, is_list=False),
    "index": FieldSchema(name="index", type=str, is_optional=True, is_list=False),
    "latest": FieldSchema(name="latest", type=str, is_optional=True, is_list=False),
    "notice_id": FieldSchema(name="notice_id", type=str, is_optional=True, is_list=False),
    "notice_type_code": FieldSchema(
        name="notice_type_code", type=str, is_optional=True, is_list=False
    ),
    "parent_notice_id": FieldSchema(
        name="parent_notice_id", type=str, is_optional=True, is_list=False
    ),
    "posted_date": FieldSchema(name="posted_date", type=date, is_optional=True, is_list=False),
    "related_notice_id": FieldSchema(
        name="related_notice_id", type=str, is_optional=True, is_list=False
    ),
    "solicitation_number": FieldSchema(
        name="solicitation_number", type=str, is_optional=True, is_list=False
    ),
    "title": FieldSchema(name="title", type=str, is_optional=True, is_list=False),
}

NOTICE_TYPE_SCHEMA: dict[str, FieldSchema] = {
    "code": FieldSchema(name="code", type=str, is_optional=True, is_list=False),
    "type": FieldSchema(name="type", type=str, is_optional=True, is_list=False),
}

OFFICERS_SCHEMA: dict[str, FieldSchema] = {
    "highly_compensated_officer_1_amount": FieldSchema(
        name="highly_compensated_officer_1_amount", type=Decimal, is_optional=True, is_list=False
    ),
    "highly_compensated_officer_1_name": FieldSchema(
        name="highly_compensated_officer_1_name", type=str, is_optional=True, is_list=False
    ),
    "highly_compensated_officer_2_amount": FieldSchema(
        name="highly_compensated_officer_2_amount", type=Decimal, is_optional=True, is_list=False
    ),
    "highly_compensated_officer_2_name": FieldSchema(
        name="highly_compensated_officer_2_name", type=str, is_optional=True, is_list=False
    ),
    "highly_compensated_officer_3_amount": FieldSchema(
        name="highly_compensated_officer_3_amount", type=Decimal, is_optional=True, is_list=False
    ),
    "highly_compensated_officer_3_name": FieldSchema(
        name="highly_compensated_officer_3_name", type=str, is_optional=True, is_list=False
    ),
    "highly_compensated_officer_4_amount": FieldSchema(
        name="highly_compensated_officer_4_amount", type=Decimal, is_optional=True, is_list=False
    ),
    "highly_compensated_officer_4_name": FieldSchema(
        name="highly_compensated_officer_4_name", type=str, is_optional=True, is_list=False
    ),
    "highly_compensated_officer_5_amount": FieldSchema(
        name="highly_compensated_officer_5_amount", type=Decimal, is_optional=True, is_list=False
    ),
    "highly_compensated_officer_5_name": FieldSchema(
        name="highly_compensated_officer_5_name", type=str, is_optional=True, is_list=False
    ),
}

PARENT_AWARD_SCHEMA: dict[str, FieldSchema] = {
    "key": FieldSchema(name="key", type=str, is_optional=True, is_list=False),
    "piid": FieldSchema(name="piid", type=str, is_optional=True, is_list=False),
}

PERIOD_OF_PERFORMANCE_SCHEMA: dict[str, FieldSchema] = {
    "current_end_date": FieldSchema(
        name="current_end_date", type=date, is_optional=True, is_list=False
    ),
    "start_date": FieldSchema(name="start_date", type=date, is_optional=True, is_list=False),
    "ultimate_completion_date": FieldSchema(
        name="ultimate_completion_date", type=date, is_optional=True, is_list=False
    ),
}

PLACE_OF_PERFORMANCE_SCHEMA: dict[str, FieldSchema] = {
    "city_name": FieldSchema(name="city_name", type=str, is_optional=True, is_list=False),
    "country_code": FieldSchema(name="country_code", type=str, is_optional=True, is_list=False),
    "country_name": FieldSchema(name="country_name", type=str, is_optional=True, is_list=False),
    "state_code": FieldSchema(name="state_code", type=str, is_optional=True, is_list=False),
    "state_name": FieldSchema(name="state_name", type=str, is_optional=True, is_list=False),
    "zip_code": FieldSchema(name="zip_code", type=str, is_optional=True, is_list=False),
}

PLACE_OF_PERFORMANCE2_SCHEMA: dict[str, FieldSchema] = {
    "city": FieldSchema(name="city", type=str, is_optional=True, is_list=False),
    "country": FieldSchema(name="country", type=str, is_optional=True, is_list=False),
    "state": FieldSchema(name="state", type=str, is_optional=True, is_list=False),
    "street_address": FieldSchema(name="street_address", type=str, is_optional=True, is_list=False),
    "zip": FieldSchema(name="zip", type=str, is_optional=True, is_list=False),
}

SECONDARY_CONTACT_SCHEMA: dict[str, FieldSchema] = {
    "email": FieldSchema(name="email", type=str, is_optional=True, is_list=False),
    "fax": FieldSchema(name="fax", type=str, is_optional=True, is_list=False),
    "full_name": FieldSchema(name="full_name", type=str, is_optional=True, is_list=False),
    "phone": FieldSchema(name="phone", type=str, is_optional=True, is_list=False),
    "title": FieldSchema(name="title", type=str, is_optional=True, is_list=False),
}

SIZE_STANDARDS_SCHEMA: dict[str, FieldSchema] = {
    "employee_limit": FieldSchema(name="employee_limit", type=str, is_optional=True, is_list=False),
    "revenue_limit": FieldSchema(name="revenue_limit", type=int, is_optional=True, is_list=False),
}

TRANSACTIONS_SCHEMA: dict[str, FieldSchema] = {
    "action_type": FieldSchema(name="action_type", type=str, is_optional=True, is_list=False),
    "description": FieldSchema(name="description", type=str, is_optional=True, is_list=False),
    "modification_number": FieldSchema(
        name="modification_number", type=int, is_optional=True, is_list=False
    ),
    "obligated": FieldSchema(name="obligated", type=Decimal, is_optional=True, is_list=False),
    "transaction_date": FieldSchema(
        name="transaction_date", type=date, is_optional=True, is_list=False
    ),
}

TRANSACTIONS2_SCHEMA: dict[str, FieldSchema] = {
    "action_type": FieldSchema(name="action_type", type=str, is_optional=True, is_list=False),
    "description": FieldSchema(name="description", type=str, is_optional=True, is_list=False),
    "modification_number": FieldSchema(
        name="modification_number", type=str, is_optional=True, is_list=False
    ),
    "obligated": FieldSchema(name="obligated", type=str, is_optional=True, is_list=False),
    "transaction_date": FieldSchema(
        name="transaction_date", type=date, is_optional=True, is_list=False
    ),
}

GENERATED_NESTED: dict[str, dict[str, FieldSchema]] = {
    "AdditionalInfo": ADDITIONAL_INFO_SCHEMA,
    "Agency": AGENCY_SCHEMA,
    "Agency2": AGENCY2_SCHEMA,
    "Ancestors": ANCESTORS_SCHEMA,
    "Attachments": ATTACHMENTS_SCHEMA,
    "AwardingOffice": AWARDING_OFFICE_SCHEMA,
    "BudgetAppropriation": BUDGET_APPROPRIATION_SCHEMA,
    "BudgetSpending": BUDGET_SPENDING_SCHEMA,
    "Children": CHILDREN_SCHEMA,
    "Current": CURRENT_SCHEMA,
    "Department": DEPARTMENT_SCHEMA,
    "Department2": DEPARTMENT2_SCHEMA,
    "Display": DISPLAY_SCHEMA,
    "FederalObligations": FEDERAL_OBLIGATIONS_SCHEMA,
    "FundingDetails": FUNDING_DETAILS_SCHEMA,
    "GrantorContact": GRANTOR_CONTACT_SCHEMA,
    "GsaElibrary": GSA_ELIBRARY_SCHEMA,
    "Historical": HISTORICAL_SCHEMA,
    "ImportantDates": IMPORTANT_DATES_SCHEMA,
    "LatestNotice": LATEST_NOTICE_SCHEMA,
    "Meta": META_SCHEMA,
    "NoticeHistory": NOTICE_HISTORY_SCHEMA,
    "NoticeType": NOTICE_TYPE_SCHEMA,
    "Officers": OFFICERS_SCHEMA,
    "ParentAward": PARENT_AWARD_SCHEMA,
    "PeriodOfPerformance": PERIOD_OF_PERFORMANCE_SCHEMA,
    "PlaceOfPerformance": PLACE_OF_PERFORMANCE_SCHEMA,
    "PlaceOfPerformance2": PLACE_OF_PERFORMANCE2_SCHEMA,
    "SecondaryContact": SECONDARY_CONTACT_SCHEMA,
    "SizeStandards": SIZE_STANDARDS_SCHEMA,
    "Transactions": TRANSACTIONS_SCHEMA,
    "Transactions2": TRANSACTIONS2_SCHEMA,
}

# container model-name -> additional field schemas (merged over base)
GENERATED_OVERLAY: dict[str, dict[str, FieldSchema]] = {
    "Agency": {
        "department": FieldSchema(
            name="department", type=dict, is_optional=True, is_list=False, nested_model="Department"
        ),
    },
    "AssistanceListing": {
        "applicant_eligibility": FieldSchema(
            name="applicant_eligibility", type=str, is_optional=True, is_list=False
        ),
        "archived_date": FieldSchema(
            name="archived_date", type=date, is_optional=True, is_list=False
        ),
        "benefit_eligibility": FieldSchema(
            name="benefit_eligibility", type=str, is_optional=True, is_list=False
        ),
        "number": FieldSchema(name="number", type=Decimal, is_optional=True, is_list=False),
        "objectives": FieldSchema(name="objectives", type=str, is_optional=True, is_list=False),
        "popular_name": FieldSchema(name="popular_name", type=str, is_optional=True, is_list=False),
        "published_date": FieldSchema(
            name="published_date", type=date, is_optional=True, is_list=False
        ),
        "title": FieldSchema(name="title", type=str, is_optional=True, is_list=False),
    },
    "AwardOffice": {
        "organization_id": FieldSchema(
            name="organization_id", type=str, is_optional=True, is_list=False
        ),
    },
    "BusinessType": {
        "code": FieldSchema(name="code", type=int, is_optional=True, is_list=False),
        "name": FieldSchema(name="name", type=str, is_optional=True, is_list=False),
    },
    "Contract": {
        "award_type": FieldSchema(
            name="award_type",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "commercial_item_acquisition_procedures": FieldSchema(
            name="commercial_item_acquisition_procedures",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "consolidated_contract": FieldSchema(
            name="consolidated_contract",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "contingency_humanitarian_or_peacekeeping_operation": FieldSchema(
            name="contingency_humanitarian_or_peacekeeping_operation",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "contract_bundling": FieldSchema(
            name="contract_bundling",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "cost_accounting_standards_clause": FieldSchema(
            name="cost_accounting_standards_clause",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "cost_or_pricing_data": FieldSchema(
            name="cost_or_pricing_data",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "domestic_or_foreign_entity": FieldSchema(
            name="domestic_or_foreign_entity",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "epa_designated_product": FieldSchema(
            name="epa_designated_product",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "evaluated_preference": FieldSchema(
            name="evaluated_preference",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "fair_opportunity_limited_sources": FieldSchema(
            name="fair_opportunity_limited_sources",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "fed_biz_opps": FieldSchema(
            name="fed_biz_opps",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "foreign_funding": FieldSchema(
            name="foreign_funding",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "information_technology_commercial_item_category": FieldSchema(
            name="information_technology_commercial_item_category",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "inherently_governmental_functions": FieldSchema(
            name="inherently_governmental_functions",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "officers": FieldSchema(
            name="officers", type=dict, is_optional=True, is_list=False, nested_model="Officers"
        ),
        "performance_based_service_acquisition": FieldSchema(
            name="performance_based_service_acquisition",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "period_of_performance": FieldSchema(
            name="period_of_performance",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="PeriodOfPerformance",
        ),
        "place_of_manufacture": FieldSchema(
            name="place_of_manufacture",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "recovered_materials_sustainability": FieldSchema(
            name="recovered_materials_sustainability",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "research": FieldSchema(
            name="research",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "sam_exception": FieldSchema(
            name="sam_exception",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "set_aside": FieldSchema(
            name="set_aside",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "subcontracting_plan": FieldSchema(
            name="subcontracting_plan",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "tradeoff_process": FieldSchema(
            name="tradeoff_process",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "transactions": FieldSchema(
            name="transactions",
            type=dict,
            is_optional=True,
            is_list=True,
            nested_model="Transactions",
        ),
        "undefinitized_action": FieldSchema(
            name="undefinitized_action",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
    },
    "Department": {
        "cgac": FieldSchema(name="cgac", type=str, is_optional=True, is_list=False),
        "congressional_justification": FieldSchema(
            name="congressional_justification", type=str, is_optional=True, is_list=False
        ),
        "description": FieldSchema(name="description", type=str, is_optional=True, is_list=False),
        "website": FieldSchema(name="website", type=str, is_optional=True, is_list=False),
    },
    "Forecast": {
        "created": FieldSchema(name="created", type=datetime, is_optional=True, is_list=False),
        "display": FieldSchema(
            name="display", type=dict, is_optional=True, is_list=False, nested_model="Display"
        ),
        "modified": FieldSchema(name="modified", type=datetime, is_optional=True, is_list=False),
        "organization_id": FieldSchema(
            name="organization_id", type=str, is_optional=True, is_list=False
        ),
        "raw_data": FieldSchema(name="raw_data", type=dict, is_optional=True, is_list=False),
    },
    "Grant": {
        "additional_info": FieldSchema(
            name="additional_info",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="AdditionalInfo",
        ),
        "forecast": FieldSchema(name="forecast", type=str, is_optional=True, is_list=False),
        "funding_details": FieldSchema(
            name="funding_details",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="FundingDetails",
        ),
        "grantor_contact": FieldSchema(
            name="grantor_contact",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="GrantorContact",
        ),
        "important_dates": FieldSchema(
            name="important_dates",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="ImportantDates",
        ),
        "opportunity_history": FieldSchema(
            name="opportunity_history", type=str, is_optional=True, is_list=False
        ),
        "organization_id": FieldSchema(
            name="organization_id", type=str, is_optional=True, is_list=False
        ),
        "synopsis": FieldSchema(name="synopsis", type=str, is_optional=True, is_list=False),
    },
    "GsaElibraryContract": {
        "uei": FieldSchema(name="uei", type=str, is_optional=True, is_list=False),
    },
    "IDV": {
        "commercial_item_acquisition_procedures": FieldSchema(
            name="commercial_item_acquisition_procedures", type=str, is_optional=True, is_list=False
        ),
        "consolidated_contract": FieldSchema(
            name="consolidated_contract", type=str, is_optional=True, is_list=False
        ),
        "contingency_humanitarian_or_peacekeeping_operation": FieldSchema(
            name="contingency_humanitarian_or_peacekeeping_operation",
            type=str,
            is_optional=True,
            is_list=False,
        ),
        "contract_bundling": FieldSchema(
            name="contract_bundling", type=str, is_optional=True, is_list=False
        ),
        "contract_financing": FieldSchema(
            name="contract_financing", type=str, is_optional=True, is_list=False
        ),
        "cost_accounting_standards_clause": FieldSchema(
            name="cost_accounting_standards_clause", type=str, is_optional=True, is_list=False
        ),
        "cost_or_pricing_data": FieldSchema(
            name="cost_or_pricing_data", type=str, is_optional=True, is_list=False
        ),
        "dod_acquisition_program": FieldSchema(
            name="dod_acquisition_program", type=str, is_optional=True, is_list=False
        ),
        "dod_transaction_number": FieldSchema(
            name="dod_transaction_number", type=str, is_optional=True, is_list=False
        ),
        "domestic_or_foreign_entity": FieldSchema(
            name="domestic_or_foreign_entity", type=str, is_optional=True, is_list=False
        ),
        "email_address": FieldSchema(
            name="email_address", type=str, is_optional=True, is_list=False
        ),
        "epa_designated_product": FieldSchema(
            name="epa_designated_product", type=str, is_optional=True, is_list=False
        ),
        "evaluated_preference": FieldSchema(
            name="evaluated_preference", type=str, is_optional=True, is_list=False
        ),
        "fair_opportunity_limited_sources": FieldSchema(
            name="fair_opportunity_limited_sources", type=str, is_optional=True, is_list=False
        ),
        "fed_biz_opps": FieldSchema(name="fed_biz_opps", type=str, is_optional=True, is_list=False),
        "fee_range_lower_value": FieldSchema(
            name="fee_range_lower_value", type=str, is_optional=True, is_list=False
        ),
        "fee_range_upper_value": FieldSchema(
            name="fee_range_upper_value", type=str, is_optional=True, is_list=False
        ),
        "fixed_fee_value": FieldSchema(
            name="fixed_fee_value", type=Decimal, is_optional=True, is_list=False
        ),
        "foreign_funding": FieldSchema(
            name="foreign_funding", type=str, is_optional=True, is_list=False
        ),
        "government_furnished_property": FieldSchema(
            name="government_furnished_property", type=str, is_optional=True, is_list=False
        ),
        "gsa_elibrary": FieldSchema(
            name="gsa_elibrary",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="GsaElibrary",
        ),
        "idv_type": FieldSchema(
            name="idv_type",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "idv_website": FieldSchema(name="idv_website", type=str, is_optional=True, is_list=False),
        "inherently_governmental_functions": FieldSchema(
            name="inherently_governmental_functions", type=str, is_optional=True, is_list=False
        ),
        "local_area_set_aside": FieldSchema(
            name="local_area_set_aside", type=str, is_optional=True, is_list=False
        ),
        "major_program": FieldSchema(
            name="major_program", type=str, is_optional=True, is_list=False
        ),
        "multiple_or_single_award_idv": FieldSchema(
            name="multiple_or_single_award_idv",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "number_of_actions": FieldSchema(
            name="number_of_actions", type=str, is_optional=True, is_list=False
        ),
        "number_of_offers_source": FieldSchema(
            name="number_of_offers_source", type=str, is_optional=True, is_list=False
        ),
        "ordering_procedure": FieldSchema(
            name="ordering_procedure", type=str, is_optional=True, is_list=False
        ),
        "performance_based_service_acquisition": FieldSchema(
            name="performance_based_service_acquisition", type=str, is_optional=True, is_list=False
        ),
        "program_acronym": FieldSchema(
            name="program_acronym", type=str, is_optional=True, is_list=False
        ),
        "recovered_materials_sustainability": FieldSchema(
            name="recovered_materials_sustainability", type=str, is_optional=True, is_list=False
        ),
        "research": FieldSchema(name="research", type=str, is_optional=True, is_list=False),
        "sam_exception": FieldSchema(
            name="sam_exception", type=str, is_optional=True, is_list=False
        ),
        "simplified_procedures_for_certain_commercial_items": FieldSchema(
            name="simplified_procedures_for_certain_commercial_items",
            type=str,
            is_optional=True,
            is_list=False,
        ),
        "small_business_competitiveness_demonstration_program": FieldSchema(
            name="small_business_competitiveness_demonstration_program",
            type=str,
            is_optional=True,
            is_list=False,
        ),
        "solicitation_identifier": FieldSchema(
            name="solicitation_identifier", type=str, is_optional=True, is_list=False
        ),
        "subcontracting_plan": FieldSchema(
            name="subcontracting_plan", type=str, is_optional=True, is_list=False
        ),
        "total_estimated_order_value": FieldSchema(
            name="total_estimated_order_value", type=Decimal, is_optional=True, is_list=False
        ),
        "tradeoff_process": FieldSchema(
            name="tradeoff_process", type=str, is_optional=True, is_list=False
        ),
        "type_of_fee_for_use_of_service": FieldSchema(
            name="type_of_fee_for_use_of_service", type=str, is_optional=True, is_list=False
        ),
        "type_of_idc": FieldSchema(
            name="type_of_idc",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "undefinitized_action": FieldSchema(
            name="undefinitized_action", type=str, is_optional=True, is_list=False
        ),
        "vehicle_uuid": FieldSchema(name="vehicle_uuid", type=str, is_optional=True, is_list=False),
        "who_can_use": FieldSchema(name="who_can_use", type=str, is_optional=True, is_list=False),
    },
    "MasSin": {
        "description": FieldSchema(name="description", type=str, is_optional=True, is_list=False),
        "expiration_date": FieldSchema(
            name="expiration_date", type=str, is_optional=True, is_list=False
        ),
        "large_category_code": FieldSchema(
            name="large_category_code", type=str, is_optional=True, is_list=False
        ),
        "large_category_name": FieldSchema(
            name="large_category_name", type=str, is_optional=True, is_list=False
        ),
        "naics_codes": FieldSchema(name="naics_codes", type=int, is_optional=True, is_list=True),
        "olm": FieldSchema(name="olm", type=bool, is_optional=True, is_list=False),
        "psc_code": FieldSchema(name="psc_code", type=int, is_optional=True, is_list=False),
        "service_comm_code": FieldSchema(
            name="service_comm_code", type=str, is_optional=True, is_list=False
        ),
        "set_aside_code": FieldSchema(
            name="set_aside_code", type=str, is_optional=True, is_list=False
        ),
        "sin": FieldSchema(name="sin", type=int, is_optional=True, is_list=False),
        "state_local": FieldSchema(name="state_local", type=bool, is_optional=True, is_list=False),
        "sub_category_code": FieldSchema(
            name="sub_category_code", type=str, is_optional=True, is_list=False
        ),
        "sub_category_name": FieldSchema(
            name="sub_category_name", type=str, is_optional=True, is_list=False
        ),
        "tdr": FieldSchema(name="tdr", type=bool, is_optional=True, is_list=False),
        "title": FieldSchema(name="title", type=str, is_optional=True, is_list=False),
    },
    "Naics": {
        "code": FieldSchema(name="code", type=int, is_optional=True, is_list=False),
        "description": FieldSchema(name="description", type=str, is_optional=True, is_list=False),
        "federal_obligations": FieldSchema(
            name="federal_obligations",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="FederalObligations",
        ),
        "size_standards": FieldSchema(
            name="size_standards",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="SizeStandards",
        ),
    },
    "OTA": {
        "award_type": FieldSchema(
            name="award_type",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "awarding_office": FieldSchema(
            name="awarding_office",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="AwardingOffice",
        ),
        "base_and_exercised_options_value": FieldSchema(
            name="base_and_exercised_options_value", type=Decimal, is_optional=True, is_list=False
        ),
        "consortia": FieldSchema(name="consortia", type=str, is_optional=True, is_list=False),
        "consortia_uei": FieldSchema(
            name="consortia_uei", type=str, is_optional=True, is_list=False
        ),
        "dod_acquisition_program": FieldSchema(
            name="dod_acquisition_program", type=int, is_optional=True, is_list=False
        ),
        "extent_competed": FieldSchema(
            name="extent_competed",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "fiscal_year": FieldSchema(name="fiscal_year", type=int, is_optional=True, is_list=False),
        "funding_office": FieldSchema(
            name="funding_office",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="AwardingOffice",
        ),
        "non_governmental_dollars": FieldSchema(
            name="non_governmental_dollars", type=Decimal, is_optional=True, is_list=False
        ),
        "non_traditional_government_contractor_participation": FieldSchema(
            name="non_traditional_government_contractor_participation",
            type=str,
            is_optional=True,
            is_list=False,
        ),
        "parent_award": FieldSchema(
            name="parent_award",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="ParentAward",
        ),
        "parent_award_modification_number": FieldSchema(
            name="parent_award_modification_number", type=int, is_optional=True, is_list=False
        ),
        "period_of_performance": FieldSchema(
            name="period_of_performance",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="PeriodOfPerformance",
        ),
        "place_of_performance": FieldSchema(
            name="place_of_performance",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="PlaceOfPerformance",
        ),
        "psc": FieldSchema(
            name="psc", type=dict, is_optional=True, is_list=False, nested_model="CodeDescription"
        ),
        "psc_code": FieldSchema(name="psc_code", type=int, is_optional=True, is_list=False),
        "transactions": FieldSchema(
            name="transactions",
            type=dict,
            is_optional=True,
            is_list=True,
            nested_model="Transactions2",
        ),
        "type_of_ot_agreement": FieldSchema(
            name="type_of_ot_agreement",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
    },
    "OTIDV": {
        "awarding_office": FieldSchema(
            name="awarding_office",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="AwardingOffice",
        ),
        "base_and_exercised_options_value": FieldSchema(
            name="base_and_exercised_options_value", type=Decimal, is_optional=True, is_list=False
        ),
        "consortia": FieldSchema(name="consortia", type=str, is_optional=True, is_list=False),
        "consortia_uei": FieldSchema(
            name="consortia_uei", type=str, is_optional=True, is_list=False
        ),
        "dod_acquisition_program": FieldSchema(
            name="dod_acquisition_program", type=str, is_optional=True, is_list=False
        ),
        "extent_competed": FieldSchema(
            name="extent_competed",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "fiscal_year": FieldSchema(name="fiscal_year", type=int, is_optional=True, is_list=False),
        "funding_office": FieldSchema(
            name="funding_office",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="AwardingOffice",
        ),
        "non_governmental_dollars": FieldSchema(
            name="non_governmental_dollars", type=Decimal, is_optional=True, is_list=False
        ),
        "non_traditional_government_contractor_participation": FieldSchema(
            name="non_traditional_government_contractor_participation",
            type=str,
            is_optional=True,
            is_list=False,
        ),
        "period_of_performance": FieldSchema(
            name="period_of_performance",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="PeriodOfPerformance",
        ),
        "place_of_performance": FieldSchema(
            name="place_of_performance",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="PlaceOfPerformance",
        ),
        "psc": FieldSchema(
            name="psc", type=dict, is_optional=True, is_list=False, nested_model="CodeDescription"
        ),
        "psc_code": FieldSchema(name="psc_code", type=int, is_optional=True, is_list=False),
        "transactions": FieldSchema(
            name="transactions",
            type=dict,
            is_optional=True,
            is_list=True,
            nested_model="Transactions2",
        ),
        "type_of_ot_agreement": FieldSchema(
            name="type_of_ot_agreement",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
    },
    "Office": {
        "agency": FieldSchema(
            name="agency", type=dict, is_optional=True, is_list=False, nested_model="Agency"
        ),
        "agency_code": FieldSchema(name="agency_code", type=str, is_optional=True, is_list=False),
        "agency_name": FieldSchema(name="agency_name", type=str, is_optional=True, is_list=False),
        "department": FieldSchema(
            name="department", type=dict, is_optional=True, is_list=False, nested_model="Department"
        ),
        "department_code": FieldSchema(
            name="department_code", type=str, is_optional=True, is_list=False
        ),
        "department_name": FieldSchema(
            name="department_name", type=str, is_optional=True, is_list=False
        ),
        "office_code": FieldSchema(name="office_code", type=str, is_optional=True, is_list=False),
        "office_name": FieldSchema(name="office_name", type=str, is_optional=True, is_list=False),
        "organization_id": FieldSchema(
            name="organization_id", type=str, is_optional=True, is_list=False
        ),
    },
    "Opportunity": {
        "agency": FieldSchema(
            name="agency", type=dict, is_optional=True, is_list=False, nested_model="Agency2"
        ),
        "agency_id": FieldSchema(name="agency_id", type=str, is_optional=True, is_list=False),
        "archive_date": FieldSchema(
            name="archive_date", type=date, is_optional=True, is_list=False
        ),
        "attachments": FieldSchema(
            name="attachments",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="Attachments",
        ),
        "department": FieldSchema(
            name="department",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="Department2",
        ),
        "department_id": FieldSchema(
            name="department_id", type=str, is_optional=True, is_list=False
        ),
        "latest_notice": FieldSchema(
            name="latest_notice",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="LatestNotice",
        ),
        "latest_notice_id": FieldSchema(
            name="latest_notice_id", type=str, is_optional=True, is_list=False
        ),
        "meta": FieldSchema(
            name="meta", type=dict, is_optional=True, is_list=False, nested_model="Meta"
        ),
        "notice_history": FieldSchema(
            name="notice_history",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="NoticeHistory",
        ),
        "office_id": FieldSchema(name="office_id", type=str, is_optional=True, is_list=False),
        "place_of_performance": FieldSchema(
            name="place_of_performance",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="PlaceOfPerformance2",
        ),
        "secondary_contact": FieldSchema(
            name="secondary_contact",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="SecondaryContact",
        ),
        "set_aside": FieldSchema(
            name="set_aside",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="CodeDescription",
        ),
        "snippet": FieldSchema(name="snippet", type=str, is_optional=True, is_list=False),
    },
    "Organization": {
        "aac_code": FieldSchema(name="aac_code", type=str, is_optional=True, is_list=False),
        "agency": FieldSchema(
            name="agency", type=dict, is_optional=True, is_list=False, nested_model="Agency"
        ),
        "ancestors": FieldSchema(
            name="ancestors", type=dict, is_optional=True, is_list=True, nested_model="Ancestors"
        ),
        "budget_appropriation": FieldSchema(
            name="budget_appropriation",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="BudgetAppropriation",
        ),
        "budget_spending": FieldSchema(
            name="budget_spending",
            type=dict,
            is_optional=True,
            is_list=False,
            nested_model="BudgetSpending",
        ),
        "canonical_code": FieldSchema(
            name="canonical_code", type=str, is_optional=True, is_list=False
        ),
        "cgac": FieldSchema(name="cgac", type=int, is_optional=True, is_list=False),
        "children": FieldSchema(
            name="children", type=dict, is_optional=True, is_list=True, nested_model="Children"
        ),
        "code": FieldSchema(name="code", type=int, is_optional=True, is_list=False),
        "department": FieldSchema(
            name="department", type=dict, is_optional=True, is_list=False, nested_model="Agency"
        ),
        "description": FieldSchema(name="description", type=str, is_optional=True, is_list=False),
        "end_date": FieldSchema(name="end_date", type=str, is_optional=True, is_list=False),
        "fpds_code": FieldSchema(name="fpds_code", type=int, is_optional=True, is_list=False),
        "fpds_org_id": FieldSchema(name="fpds_org_id", type=int, is_optional=True, is_list=False),
        "full_parent_path_name": FieldSchema(
            name="full_parent_path_name", type=str, is_optional=True, is_list=False
        ),
        "is_active": FieldSchema(name="is_active", type=bool, is_optional=True, is_list=False),
        "l1_fh_key": FieldSchema(name="l1_fh_key", type=int, is_optional=True, is_list=False),
        "l2_fh_key": FieldSchema(name="l2_fh_key", type=int, is_optional=True, is_list=False),
        "l3_fh_key": FieldSchema(name="l3_fh_key", type=int, is_optional=True, is_list=False),
        "l4_fh_key": FieldSchema(name="l4_fh_key", type=str, is_optional=True, is_list=False),
        "l5_fh_key": FieldSchema(name="l5_fh_key", type=str, is_optional=True, is_list=False),
        "l6_fh_key": FieldSchema(name="l6_fh_key", type=str, is_optional=True, is_list=False),
        "l7_fh_key": FieldSchema(name="l7_fh_key", type=str, is_optional=True, is_list=False),
        "l8_fh_key": FieldSchema(name="l8_fh_key", type=str, is_optional=True, is_list=False),
        "logo": FieldSchema(name="logo", type=str, is_optional=True, is_list=False),
        "mod_status": FieldSchema(name="mod_status", type=str, is_optional=True, is_list=False),
        "obligation_rank": FieldSchema(
            name="obligation_rank", type=str, is_optional=True, is_list=False
        ),
        "obligations": FieldSchema(
            name="obligations", type=Decimal, is_optional=True, is_list=False
        ),
        "parent": FieldSchema(
            name="parent", type=dict, is_optional=True, is_list=False, nested_model="Children"
        ),
        "parent_fh_key": FieldSchema(
            name="parent_fh_key", type=int, is_optional=True, is_list=False
        ),
        "start_date": FieldSchema(
            name="start_date", type=datetime, is_optional=True, is_list=False
        ),
        "summary": FieldSchema(name="summary", type=str, is_optional=True, is_list=False),
        "total_obligations": FieldSchema(
            name="total_obligations", type=Decimal, is_optional=True, is_list=False
        ),
        "tree_obligations": FieldSchema(
            name="tree_obligations", type=Decimal, is_optional=True, is_list=False
        ),
    },
    "PSC": {
        "category": FieldSchema(name="category", type=str, is_optional=True, is_list=False),
        "code": FieldSchema(name="code", type=int, is_optional=True, is_list=False),
        "current": FieldSchema(
            name="current", type=dict, is_optional=True, is_list=False, nested_model="Current"
        ),
        "historical": FieldSchema(
            name="historical", type=dict, is_optional=True, is_list=True, nested_model="Historical"
        ),
        "level_1_category": FieldSchema(
            name="level_1_category", type=str, is_optional=True, is_list=False
        ),
        "level_1_category_code": FieldSchema(
            name="level_1_category_code", type=int, is_optional=True, is_list=False
        ),
        "level_2_category": FieldSchema(
            name="level_2_category", type=str, is_optional=True, is_list=False
        ),
        "level_2_category_code": FieldSchema(
            name="level_2_category_code", type=Decimal, is_optional=True, is_list=False
        ),
        "parent": FieldSchema(name="parent", type=str, is_optional=True, is_list=False),
    },
}
